name: Docker

on:
  push:
    branches: ['docker-tags']
  pull_request:
    branches: ['docker-tags']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME:  ${{ github.repository }}-recommender



jobs:
  test-and-code-coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install lcov
        run: sudo apt-get install -y lcov

      - name: cleanup
        run: make purge

      - name: compile
        run: make
      
      - name: test
        run: make test
      
      - name: code coverage
        run: make coverage    
      
      - name: display code coverage
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: ./coverage.info 

  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: cleanup
        run: make purge
        
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Extract metadata (tags, labels) for Docker Alpine
        id: metaalpine
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker Alpine image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.metaalpine.outputs.tags }}-alpine, ${{ steps.metaalpine.outputs.tags }}-alpine3.14.6
          labels: ${{ steps.metaalpine.outputs.labels }}
          file: alpine.Dockerfile
          
      - name: Extract metadata (tags, labels) for Docker Debian
        id: metadebian
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          
      - name: Build and push Docker Debian image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.metadebian.outputs.tags }}-debian, ${{ steps.metadebian.outputs.tags }}-debian9.13
          labels: ${{ steps.metadebian.outputs.labels }}
          file: debian.Dockerfile