name: CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: [ master ]

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: tag alpine
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "v1.0.0-alpine"
          message: "Latest release"
